### PR TITLE
fixes #152

### LINKED ISSUE #152: Bug with AliasPathStackResolver
Today I encountered a bug with AliasPathStackResolver. If the alias string exists in the assets path, then asset is not resolved. This is because of [this line](https://github.com/RWOverdijk/AssetManager/blob/865eebdd404fc47dfa961f7ae3453c70712e3857/src/AssetManager/Resolver/AliasPathStackResolver.php#L145).

For example,
```php
// in module/Configuration/config/module.config.php
return [
    'asset_manager' => [
        'resolver_configs' => [
            'aliases' => [
                'configuration' => __DIR__ . '/../public',
            ]
        ]
    ],
]:
```

Now, if some javascript file exists like `module/Configuration/public/js/configuration.js`, this is not  resolved. But some javascript file like `module/Configuration/public/js/module.js` is resolved.

### PR DESCRIPTION
**Pull request by ojhaujjwal**
fixes #152. Fixes bug with AliasPathStackResolver when alias string exists in asset path

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@ojhaujjwal Are you willing to modify the test for us?

**Comment by ojhaujjwal** [comment]
@RWOverdijk Sorry. I forgot this. I will do it. :D

**Comment by RWOverdijk** [comment]
@ojhaujjwal You're awesome

**Comment by RWOverdijk** [comment]
@Ocramius I'm sold on this. Do you agree?

**Comment by Ocramius** [comment]
Except for minor CS nitpicking, looks good.

**Comment by RWOverdijk** [comment]
Thanks!

**Pull request merged**
