### PR TITLE
Fix for #159

### PR DESCRIPTION
**Pull request by ojhaujjwal**

### CODE REVIEW

**Comment by Ocramius** [comment]
Tests

**Comment by RWOverdijk** [comment]
What he meant was, could you please add some tests that prove what you've fixed is fixed? So failing and succeeding cases.

**Comment by ojhaujjwal** [comment]
Any comments now?

**Comment by RWOverdijk** [comment]
@Ocramius Looks good to me. Previous test still passes, the code is fine and the other end of the tests is also included.

**Comment by Ocramius** [comment]
:+1:

**Pull request merged**
