### PR TITLE
[BC break] Remove ZF2 + PSR-11

### PR DESCRIPTION
**Pull request by wshafer**
Sets the minimum requirement to ZF3 and replaces deprecated container-interop to PSR-11

Other updates:
Vagrant file taken from ZF Skeleton for quick development (can be removed if needed)
Removed composer.lock file

### CODE REVIEW

**Comment by wshafer** [comment]
FYI - Tests do pass, but Travis-CI's HHVM image is currently broken.   Upstream issue created.

https://github.com/travis-ci/travis-ci/issues/7712

**Comment by wshafer** [comment]
FYI - If I'm reading the upstream issue right, HHVM looks like it will not be fixed on Precise builds.  Gonna leave Trusty as the build OS for now.

**Comment by RWOverdijk** [comment]
You've been going at it! But I agree, that's a fair solution for now.

**Comment by Ocramius** [comment]
FWIW, supporting HHVM is not priority in most larger frameworks anymore, so
if you feel like it's holding you back, I suggest dropping it from builds.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by wshafer** [comment]
@RWOverdijk - If you agree I'll yank HHVM from the Travis build.

**Comment by wshafer** [comment]
Never mind...  what was I thinking.  Precise is EOL anyway and we should be testing against Trusty.

**Comment by RWOverdijk** [comment]
@wshafer Also, it's running now. Might as well keep it in, right? :)

**Comment by RWOverdijk** [comment]
@wshafer Maybe this should be closed?

**Comment by wshafer** [comment]
Yep.  I'll have a new and improved one soon.

**Pull request closed without merging**
