### PR TITLE
Allow use of URLs as assets

### PR DESCRIPTION
**Pull request by internalsystemerror**
Cleanup of https://github.com/RWOverdijk/AssetManager/pull/87

### CODE REVIEW

**Comment by FabianKoestring** [comment]
> Would you be so kind to update the wiki concerning this new feature?

Cant find any information!

**Comment by RWOverdijk** [comment]
@FabianKoestring That makes sense. You can just use the full url in a map config. If that works, let me know so we can update the wiki. :)

**Comment by FabianKoestring** [comment]
Yea it works that way. But only if the url ends with .css or .js. Something like googlefonts doesnt work. I got it work if i put .css at the end of the url.
It would be better if the mimetype is detected via the response and not via filetype.

**Comment by internalsystemerror** [comment]
(its all coming back to me now) I remember there being an issue at times with css from certain sources returning a text/html mime type incorrectly. Something to consider.

**Comment by FabianKoestring** [comment]
@RWOverdijk - Just to make things clear. I would like to create a PR to solve this problem. What are youre thoughts about adding a function `getUrlMimeType($url)` in `MimeResolver.php` which gets called on `HttpAssets`. Otherwise the default `getMimeTyp($file)` function will detect the mime-type.

If this is ok for you i will create a PR. Or do you have other thoughts on this?

**Comment by RWOverdijk** [comment]
@FabianKoestring Maybe move this over to a new issue?

**Comment by RWOverdijk** [comment]
@FabianKoestring Anyway, I do sort of agree. The thing is that for files we use the extension. Perhaps we should do the same for external urls, the way it should be done?

**Pull request merged**
