### PR TITLE
added missing filter in warmupAction

### PR DESCRIPTION
**Pull request by hummer2k**
Issue #165

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@sokac Mind taking a look? :)

**Comment by sokac** [comment]
It looks good, don't see any problems.

**Comment by RWOverdijk** [comment]
@sokac So you can confirm that filters were never applied to collections?

**Comment by RWOverdijk** [comment]
@hummer2k Thanks! Could you perhaps add some tests to confirm this works? There's a JSMin test I believe you can use as a base for it.

**Pull request merged**
