### PR TITLE
Fix ViewHelper Configuration

### LINKED ISSUE #214: Asset view helper not work with ZF3 with basic documentation configuration. ZF3 use his own Asset view helper.
Actual configuration for helper is, probably work with ZF2, but not with ZF3:

```
'view_helpers'    => [
        'factories' => [
            'asset' => AssetManager\Service\AssetViewHelperFactory::class,
        ],
 ],
```

To work properly with ZF3 should be:

```
'factories' => [
            AssetManager\View\Helper\Asset::class => AssetManager\Service\AssetViewHelperFactory::class,
        ],
        'aliases' => [
            'asset' => AssetManager\View\Helper\Asset::class
        ],
],
```

Also there is a lack of documentation, how to use i.e. cache busting, for assets. For many of us it is obvious, but not for all. Anyway IMHO should be added just for clarification.

### PR DESCRIPTION
**Pull request by FabianKoestring**
fix #214

To work with the new introduced Zend ViewHelper `Zend\View\Helper\Asset` the configuration of AssetManager ViewHelper `asset` has to be changed.

@wshafer

### CODE REVIEW

**Comment by RWOverdijk** [comment]
At first glance this seems harmless. The alias should make sure it's BC...

LGTM but like I said on twitter, I do want @wshafer to bestow his infinite wisdom upon this PR.

**Comment by RWOverdijk** [comment]
Also: tests seem to fail because of hhvm. But really... HHVM? who cares.

**Comment by wshafer** [comment]
There’s nothing really changing here other then making this follow the current flow of Zend.

Hhvm is also no longer supported by Zend so I agree who cares?  Perhaps we should just pull it from the Travis file?

I am a little confused how this commit will make it work and the other doesn’t work.  The plugin manager is just an instance of the service manager so it should still find the service just fine when defined as a factory key.  

That said I see nothing dangerous here.

**Comment by RWOverdijk** [comment]
Your confusion is shared.

Anyway, if you say go, it's go and it can be merged and tagged.

**Comment by RWOverdijk** [comment]
I'll try to do this on Monday. Here's to hoping I'll remember :p

**Comment by FabianKoestring** [comment]
> I'll try to do this on Monday. Here's to hoping I'll remember :p

Just a reminder... 😄

**Comment by RWOverdijk** [comment]
Thanks for the reminder :)

**Comment by FabianKoestring** [comment]
Thanks @RWOverdijk for merging. Packagist (https://packagist.org/packages/rwoverdijk/assetmanager) cant find the new release. Is this normal behavior?

**Comment by RWOverdijk** [comment]
You're impatient aren't you haha.

Packagist has update cycles. But I've manually updated it just for you. ❤️

**Comment by Ocramius** [comment]
@RWOverdijk I think you need to log out and then back into packagist via github OAuth - the update mechanism changed recently.

**Pull request merged**
