### PR TITLE
Migrate RWOverdijk/AssetManager to laminas with laminas-migration tool

### PR DESCRIPTION
**Pull request by larsvandersangen**
Hello RWOverdijk,

I've created a branch that has been updated to be compatible with the Laminas instead of zend-framework. Of course accompanied by the PHP and PHPUnit updates that are required by this migration (minimal PHP 7.2 and PHPUnit 7.0.0). Successful builds for PHP 7.2 through 7.4 are [here](https://travis-ci.com/larsvandersangen/AssetManager). This migration has been executed with the help of https://docs.laminas.dev/migration/.

Please do give your feedback if you think this PR can be enhanced, improved or is in some way faulty.

The reason I'm creating this PR is because I work for a company that wishes to migrate to Laminas. But this library is one of the libraries that is holding us back because it has no version available that is compatible with Laminas.

Greets LLTM

### CODE REVIEW

**Comment by RWOverdijk** [comment]
@larsvandersangen Could you add a notice in the readme? Something like "> 1.8.1 < 2.0.0 for zf, > 2.0.0 laminas".

Just a description so it's clear what people should use / PR to.

As to reviewing this I'll give it a go, and then suggest to release it and patch it as we go.

**Comment by larsvandersangen** [comment]
@RWOverdijk, is this good enough? Or do you want a seperate paragraph explaining this?

**Comment by RWOverdijk** [comment]
No, this looks good to me. @wshafer Do you have an opinion on this PR?

**Comment by FrankHouweling** [comment]
@RWOverdijk @wshafer Is there any info on this?

**Comment by RWOverdijk** [comment]
Executive decision. 😄 I'll tag it.

**Pull request merged**
