### PR TITLE
Migration to Assetic framework

### PR DESCRIPTION
**Pull request by thomasvargiu**
Assetic is not mainteined anymore and a new fork is born: https://github.com/assetic-php/assetic

This PR (wip) replaces assetic with the new fork.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Nice :) Could we get some more eyes on this?

**Comment by thomasvargiu** [comment]
That library is still in development, but I've already tried this fork on my project and everything's fine. Of course I'm not using all features.

I added a PSR Simple Cache Adapter too.

You can review it, but I would wait for a stable release of the new assetic: https://github.com/assetic-php/assetic

**Comment by pimjansen** [comment]
@RWOverdijk isnt that lib good enough now? Since actually with the current setup and Assetic it will break right? It consumes a very old version of symfony/process which will block others

**Comment by RWOverdijk** [comment]
As long as that lib is in dev and not stable, no. A pre-release could be made, of course, by then I'd first like some more eyes on this to confirm that's a good idea.

**Comment by pimjansen** [comment]
We are using it atm without any issues though however i dont have a clue on how assetic works. Since it is completely dead it will be pretty hard i guess.

**Comment by svycka** [comment]
@RWOverdijk 
> As long as that lib is in dev and not stable, no. A pre-release could be made, of course, by then I'd first like some more eyes on this to confirm that's a good idea.

new stable release: https://github.com/assetic-php/assetic/releases/tag/v2.0.0

**Comment by RWOverdijk** [comment]
Cool stuff! Where can I reach you? You seem to be willing to work on this so I want to give you the keys :)

**Pull request closed without merging**
