### PR TITLE
Bump minimal php requirement to 7.3

### PR DESCRIPTION
**Pull request by adamturcsan**
Used dependency (ie. laminas/laminas-dependency-plugin) already requires this

### CODE REVIEW

**Comment by adamturcsan** [comment]
If there's anything that needs to be changed for php:^7.3 I'll try to follow.

There are quite old dependencies that could be updated also if php7.2 support is not required. I'll look into it, if necessary, but honestly I just want to push for a release to use this with up-to-date environment ASAP.

**Comment by adamturcsan** [comment]
Ok, so it didn't caught my attention that the 2.1.0 tag was already made(packagist crawler hasn't noticed it either), so now I could use the lib if packagist notices :+1: 
But the CI is still failing, the php:^7.2 requirement is still false, so here it is :)

**Comment by RWOverdijk** [comment]
You're right, that was messy of me. Thanks for this.

**Comment by adamturcsan** [comment]
Ehm, could you tell me, why haven't you merged this?
https://github.com/RWOverdijk/AssetManager/compare/2.1.0...2.1.1 It shows no changes :(  I assume the CI will also fail (it recieved a job for 7.2)

**Comment by RWOverdijk** [comment]
I thought I did hit merge... Chaotic day.

**Comment by adamturcsan** [comment]
The point is we sorted it out. Thank you! :)

**Pull request merged**
